# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lh1VzKWB_qbwU2Qy2OB5SMLg7Xzly4Er
"""



#este simbolo se utiliza para comentar.
print("Hola grupo 430 de la carrera tecnica de programacion")
#como consultar el tipo de dato
print(type("soy un dato str")) #tipo"str"
print(type(5)) #tipo"int"
print(type(1.5)) #tipo"float"
print(type(3 + 1j)) #tipo"complex"
print(type(True)) #tipo"bool"
print(type(print("mi cadena de texto"))) #tipo"NoneType"