# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lh1VzKWB_qbwU2Qy2OB5SMLg7Xzly4Er
"""

## Loops ###

my_condition = 0

while my_condition < 10:
  print(my_condition)
  my_condition += 2

else: #Es opcional
   print("Mi condicional es mayor o igual que 10")

print("La ejecución continua")

while my_condition < 20:
  my_condition += 1
  if my_condition == 15:
    print("Se detiene la ejecución")
    break

  print(my_condition)

print("La ejecución continua")


# For

my_list = [35, 24,62, 52, 30, 30, 17]

for element in my_list:
  print(element)

my_tuple = (35, 1.75, "kenny", "bucio", "Christian" )

for element in my_tuple:
  print(element)

my_set = {"kenny", "bucio", 35}

for element in my_set:
  print(element)

my_dict = {"Nombre": "kenny", "Apellido": "bucio", "Edad": 17, 1: "Python"}

for element in my_dict:
  print(element)
  if element == "Edad":
    break
    print("Se ejecuta")
else:
  print("El ciclo for para diccionario ha finalizado")


my_dict = {"Nombre": "kenny", "Apellido": "bucio", "Edad": 17, 1: "Python"}

for element in my_dict:
  print(element)
  if element == "Edad":
    continue
    print("Se ejecuta")
else:
  print("El ciclo for para diccionario ha finalizad")